steps:
  # running docker-compose
  - name: 'node'
    entrypoint: 'yarn'
    args: ['install']
  - name: 'node'
    entrypoint: 'yarn'
    args: ['yarn', 'plugin', 'import', 'workspace-tools']

  - name: 'node'
    entrypoint: 'yarn'
    args: ['build']
  - name: 'docker/compose:1.26.2'
    args: ['up', '-d']
