version: '3.3'
services:
  db:
    container_name: db
    env_file:
      - ./.env
    expose:
      - '3001'
    image: postgres
    networks:
      - network
    ports:
      - 3001:5432
    restart: always
    volumes:
      - ./pizza-store-backend/dbinit:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

  postgrest:
    container_name: postgrest
    depends_on:
      - db
    env_file:
      - ./.env
    expose:
      - '3000'
    image: postgrest/postgrest
    networks:
      - network
    ports:
      - 3000:3000
    restart: always

  # swagger:
  #   container_name: swagger
  #   depends_on:
  #     - postgrest
  #   environment:
  #     API_URL: http://localhost:3000/
  #   expose:
  #     - '3002'
  #   image: swaggerapi/swagger-ui
  #   networks:
  #     - network
  #   ports:
  #     - 3002:8080
  #   restart: always

  app:
    container_name: app
    depends_on:
      - postgrest
    expose:
      - '80'
    image: nginx:mainline-alpine
    networks:
      - network
    ports:
      - 80:80
    restart: always
    volumes:
      - ./pizza-store-frontend/dist:/usr/share/nginx/html
networks:
  network:
    driver: bridge

volumes:
  data:
