# FROM node:16 as builder
# WORKDIR /app
# COPY ./pizza-store-frontend/* ./
# # RUN npm install --global yarn
# RUN yarn install
# RUN yarn build


FROM nginx:mainline-alpine
# WORKDIR /app
# COPY --from=builder /app/dist /usr/share/nginx/html