version: '3.3'
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile-db
    container_name: db
    env_file:
      - ./.env
    expose:
      - '3001'
    image: gcr.io/pizza-man-391321/pizza/db:latest
    networks:
      - network
    ports:
      - 3001:5432
    restart: always
    volumes:
      - ./pizza-store-backend/dbinit:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

  postgrest:
    build:
      context: ./
      dockerfile: Dockerfile-postgrest
    container_name: postgrest
    depends_on:
      - db
    env_file:
      - ./.env
    expose:
      - '3000'
    image: gcr.io/pizza-man-391321/pizza/postgrest:latest
    networks:
      - network
    ports:
      - 3000:3000
    restart: always

  app:
    build:
      context: ./
      dockerfile: Dockerfile-app
    container_name: app
    depends_on:
      - postgrest
    expose:
      - '80'
    image: gcr.io/pizza-man-391321/pizza/app:latest
    networks:
      - network
    ports:
      - 80:80
    restart: always
    volumes:
      - ./pizza-store-frontend/dist:/usr/share/nginx/html
networks:
  network:
    driver: bridge

volumes:
  data:
